// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfIEyF4kHDDTWzkU_RgOJTgCsg9T5Lubk',
    appId: '1:37211630046:web:3e2a6eeecb19d2a19a554f',
    messagingSenderId: '37211630046',
    projectId: 'imitage-sirloin',
    authDomain: 'imitage-sirloin.firebaseapp.com',
    storageBucket: 'imitage-sirloin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgNNeXOk2CzrgFQE7XokuCpCXpQpQiR5g',
    appId: '1:37211630046:android:cbd08d73a2bb9e1d9a554f',
    messagingSenderId: '37211630046',
    projectId: 'imitage-sirloin',
    storageBucket: 'imitage-sirloin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqAIkbXXMk5-5WjycBdaPW9a-D-QIcLT8',
    appId: '1:37211630046:ios:9c4bd7c71d2ca95d9a554f',
    messagingSenderId: '37211630046',
    projectId: 'imitage-sirloin',
    storageBucket: 'imitage-sirloin.appspot.com',
    iosClientId: '37211630046-pnjt96nurue003901ib1i6m0a749ota7.apps.googleusercontent.com',
    iosBundleId: 'com.sirloin.imitateSirloin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqAIkbXXMk5-5WjycBdaPW9a-D-QIcLT8',
    appId: '1:37211630046:ios:9c4bd7c71d2ca95d9a554f',
    messagingSenderId: '37211630046',
    projectId: 'imitage-sirloin',
    storageBucket: 'imitage-sirloin.appspot.com',
    iosClientId: '37211630046-pnjt96nurue003901ib1i6m0a749ota7.apps.googleusercontent.com',
    iosBundleId: 'com.sirloin.imitateSirloin',
  );
}
